// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBClw80pweCONmcLDRNYmU4EP_-bEUpYf8',
    appId: '1:569533417494:web:9b58cd110122b3b1ab4d37',
    messagingSenderId: '569533417494',
    projectId: 'pokedex-762ef',
    authDomain: 'pokedex-762ef.firebaseapp.com',
    storageBucket: 'pokedex-762ef.firebasestorage.app',
    measurementId: 'G-BL6CFPBHT3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg2QnkbQg2s_gnpZto_d4G1Qs0YLZeT6A',
    appId: '1:569533417494:android:dd9059542eaf9174ab4d37',
    messagingSenderId: '569533417494',
    projectId: 'pokedex-762ef',
    storageBucket: 'pokedex-762ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm7YR6UsTUga-tKhfllyzLkwJRVIWA4Ek',
    appId: '1:569533417494:ios:c3c7c195dacdf548ab4d37',
    messagingSenderId: '569533417494',
    projectId: 'pokedex-762ef',
    storageBucket: 'pokedex-762ef.firebasestorage.app',
    iosBundleId: 'com.example.appPokemon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm7YR6UsTUga-tKhfllyzLkwJRVIWA4Ek',
    appId: '1:569533417494:ios:c3c7c195dacdf548ab4d37',
    messagingSenderId: '569533417494',
    projectId: 'pokedex-762ef',
    storageBucket: 'pokedex-762ef.firebasestorage.app',
    iosBundleId: 'com.example.appPokemon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBClw80pweCONmcLDRNYmU4EP_-bEUpYf8',
    appId: '1:569533417494:web:1df3684e4e348b97ab4d37',
    messagingSenderId: '569533417494',
    projectId: 'pokedex-762ef',
    authDomain: 'pokedex-762ef.firebaseapp.com',
    storageBucket: 'pokedex-762ef.firebasestorage.app',
    measurementId: 'G-DF8VT86PX0',
  );
}
